name: Update Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://yoonky-kor.github.io/index.xml"
          max_post_count: 3
          readme_path: README.md
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          url_filter: "about,tags,categories"
          template: "- [$title]($url)"
          date_format: "yyyy-MM-dd"
